const genreColors = {
    "Rock": "#e63946",
    "Pop": "#ffbe0b",
    "J-Pop": "#3a86ff",
    "Jazz": "#8338ec",
    "Electronic": "#ff006e",
    "Alternative": "#06d6a0",
    "Indie Pop": "#8d99ae",
    "Samba": "#f4a261",
    "Metal": "#2b2d42",
    "Death Metal": "#2d2d2d",
    "Folk":"#823329",
    "Soul":"#823329",
    "Acid Jazz":"#3F612D",
    "Hip-Hop":"#918450",
    "New Wave":"#A44A3F",

};

const songs = [
    { title:"Paranoia", artist:"The Marías", duration:	231786, vibe: 1, genre: "Alternative",link: "spotify:track:4gtIYSYu8u2ItBqrhCaChL"},
    { title:"It's Me & You", artist:"Tokyo Tea Room", duration:	218492, vibe: 1, genre: "Pop",link: "spotify:track:2j32Q0EtMeEYhRfqVOlprO"},
    { title:"He Asked Me to Quit Smoking", artist:"BUBBLE TEA AND CIGARETTES", duration:	181747, vibe: 1, genre: "Alternative",link: "spotify:track:1CrzyYbSTUattgIzNMzL3u"},
    { title:"Night Vision", artist:"Vansire, Barrie", duration:	117733, vibe: 1, genre: "Electronic",link: "spotify:track:1MwPvniPtqPkXwtQDFiJdb"},
    { title:"Real Life", artist:"The Marías", duration:	206973, vibe: 1, genre: "Rock",link: "spotify:track:3HVRZxCp3BWYuYe8L8BMNH"},
    { title:"Ice Melt", artist:"Crumb", duration:	148946, vibe: 1, genre: "Alternative",link: "spotify:track:1OPkXWnIK8RYyWTp3NWvM9"},
    { title:"ice cream days", artist:"minji", duration:	225830, vibe: 1, genre: "Indie Pop",link: "spotify:track:64bXxZxyOKzWRdjwOTBmR0"},
    { title:"If You Love Her", artist:"Tokyo Tea Room", duration:	164083, vibe: 1, genre: "Pop",link: "spotify:track:02l8T7IJ5UQE19m8cjY20f"},
    { title:"Cigarette Butt", artist:"BUBBLE TEA AND CIGARETTES", duration:	200158, vibe: 1, genre: "Alternative",link: "spotify:track:6pKiW0lfEOlJEZA1fv5ItS"},
    { title:"Eleven Weeks", artist:"Vansire", duration:	185682, vibe: 1, genre: "Alternative",link: "spotify:track:0jx2hPIzs7bNveWHU2Ohzu"},
    { title:"Is there free breakfast here?", artist:"Hotel Ugly", duration:	129199, vibe: 1, genre: "Alternative",link: "spotify:track:30jui3PqevssdIVpjEWM38"},
    { title:"Run Your Mouth", artist:"The Marías", duration:	160000, vibe: 2, genre: "Rock",link: "spotify:track:19fKJrO9XdOf6Xla2QHecO"},
    { title:"Love Costs", artist:"Love Spells", duration:	195056, vibe: 2, genre: "Soul",link: "spotify:track:7aJDtyNcnlx8a1P60uqmNn"},
    { title:"Tell Me How", artist:"Tokyo Tea Room", duration:	197389, vibe: 2, genre: "Pop",link: "spotify:track:051DhNFTui0IItRIRL5Mvj"},
    { title:"5AM Empanada with You", artist:"BUBBLE TEA AND CIGARETTES", duration:	341186, vibe: 2, genre: "Alternative",link: "spotify:track:5zotLA21Q8MnILdUxBEPRM"},
    { title:"Years Roll By", artist:"Vansire, MUNYA, JORDANN", duration:	189475, vibe: 2, genre: "Folk",link: "spotify:track:0pVG9Vj40uY2Z7D4afDEPT"},
    { title:"Heaven Knows", artist:"54 Ultra", duration:	181920, vibe: 2, genre: "Rock",link: "spotify:track:5Hg1m5uhSPL75ejQgPOmyc"},
    { title:"Waltzing Back", artist:"No Vacation", duration:	192000, vibe: 2, genre: "Alternative",link: "spotify:track:3JcvpTfI64SmXxUl7XUvQI"},
    { title:"Ghostride", artist:"Crumb", duration:	126120, vibe: 2, genre: "Alternative",link: "spotify:track:0R3TWpoxAhT3HDXM7tpRzS"},
    { title:"Forever out of Time", artist:"Tokyo Tea Room", duration:	170000, vibe: 2, genre: "Alternative",link: "spotify:track:4mZGpebzw2usDBsUc8FPhZ"},
    { title:"Room 907", artist:"BUBBLE TEA AND CIGARETTES", duration:	214500, vibe: 2, genre: "Alternative",link: "spotify:track:1N7QcezvhTp3sAQzmdxeAo"},
    { title:"Shade Your Way", artist:"Chic Chameleon", duration:	226821, vibe: 2, genre: "Alternative",link: "spotify:track:4Zj7z6KymUYPkU1qbvfZrv"},
    { title:"Some Nights", artist:"Estie Lorie", duration:	180882, vibe: 2, genre: "Indie Pop",link: "spotify:track:2vHMO3NaB2blJpW7dQktOJ"},
    { title:"smile again", artist:"she's green", duration:	235055, vibe: 2, genre: "Pop",link: "spotify:track:596IkZP89HvFYdgOb3lNvP"},
    { title:"favorite apple", artist:"The Tulips", duration:	148672, vibe: 2, genre: "Alternative",link: "spotify:track:6QT2opl34mmmeNNKZJoKUt"},
    { title:"There's A Place", artist:"Tokyo Tea Room", duration:	169055, vibe: 2, genre: "Rock",link: "spotify:track:1twDCOi0Qi28Vxu4v6K0WC"},
    { title:"Santa Monica", artist:"BUBBLE TEA AND CIGARETTES", duration:	344697, vibe: 3, genre: "Alternative",link: "spotify:track:39xjaG10Vuc1siATyqxNqZ"},
    { title:"Won't You Love Me Again?", artist:"Chic Chameleon", duration:	217802, vibe: 3, genre: "Pop",link: "spotify:track:5uUTgLDcZP71guYn3AQqwW"},
    { title:"Love You Anyway", artist:"The Marías", duration:	237133, vibe: 3, genre: "Pop",link: "spotify:track:3vxvz0JoRDvnx2jG9oPljA"},
    { title:"Baby Baby", artist:"Sports", duration:	182601, vibe: 3, genre: "Pop",link: "spotify:track:41HyMiZSBLGlfopnDE7Ppc"},
    { title:"Open My Door", artist:"Alice Phoebe Lou", duration:	153110, vibe: 3, genre: "Alternative",link: "spotify:track:1A8QcZJKhUmJwdqzoAahvR"},
    { title:"Nobody's Perfect", artist:"Tokyo Tea Room", duration:	160754, vibe: 3, genre: "Pop",link: "spotify:track:4r1yQfwjeQL9xrX1fbOdsD"},
    { title:"Happiness", artist:"BUBBLE TEA AND CIGARETTES", duration:	180018, vibe: 3, genre: "Alternative",link: "spotify:track:2nq0PFvreFTqvwN1FLlzwY"},
    { title:"Swan", artist:"Jakob", duration:	158026, vibe: 3, genre: "Alternative",link: "spotify:track:2n4hJBLbxY8rCmehI43Hzg"},
    { title:"Précis Two", artist:"Vansire, Ivy Sole", duration:	72000, vibe: 3, genre: "Alternative",link: "spotify:track:5LiO40bi3foQNkIDg4PlGV"},
    { title:"Love Songs", artist:"Clairo", duration:	178352, vibe: 3, genre: "Pop",link: "spotify:track:7wei8Hb9DxoVKUOIIAhDEQ"},
    { title:"Spanish in Chinese", artist:"Zeauxi", duration:	105321, vibe: 3, genre: "Alternative",link: "spotify:track:29Qre8uUWCuPUz8Oem2MYI"},
    { title:"Waiting By The Phone", artist:"Tokyo Tea Room", duration:	134765, vibe: 3, genre: "Pop",link: "spotify:track:1qRGnkgJMnSCZhjxlNh5Gp"},
    { title:"Liz", artist:"BUBBLE TEA AND CIGARETTES", duration:	288455, vibe: 4, genre: "Alternative",link: "spotify:track:6twViLiQLG2ZtqUrMs34l1"},
    { title:"Too Little Too Late", artist:"Boh Doran", duration:	217081, vibe: 4, genre: "Pop",link: "spotify:track:3Ziys0cjD0QpGMDJydVlIv"},
    { title:"owls eye", artist:"ivri", duration:	150824, vibe: 4, genre: "Alternative",link: "spotify:track:27yGzL2nQ3qj5l12Bni631"},
    { title:"Juna", artist:"Clairo", duration:	195109, vibe: 4, genre: "Alternative",link: "spotify:track:2mWfVxEo4xZYDaz0v7hYrN"},
    { title:"You Are the Right One", artist:"Sports", duration:	172506, vibe: 4, genre: "Indie Pop",link: "spotify:track:2qpacEyFxmbxCpIEqZkqvC"},
    { title:"No Rush", artist:"Tokyo Tea Room", duration:	264454, vibe: 4, genre: "Alternative",link: "spotify:track:3MItQB5JGZqWMMZsGOq9BG"},
    { title:"French Movie", artist:"BUBBLE TEA AND CIGARETTES", duration:	198750, vibe: 4, genre: "Alternative",link: "spotify:track:2i0v0NAwbzNKhiJRaaWdhi"},
    { title:"Lejos de Ti", artist:"The Marías", duration:	179520, vibe: 5, genre: "Pop",link: "spotify:track:0phzfJn8NeT1LkbqfV2peI"},
    { title:"my forever", artist:"Orchid Mantis, Jordana", duration:	202500, vibe: 5, genre: "Alternative",link: "spotify:track:03pUuaW00pMoqaUOJYhHRp"},
    { title:"blossom", artist:"The Tulips", duration:	150272, vibe: 5, genre: "Alternative",link: "spotify:track:1XttACqLBTsxeyegtr1VbV"},
    { title:"Stuck In Heaven", artist:"VARIATION", duration:	102295, vibe: 5, genre: "Alternative",link: "spotify:track:2vvirQ7nFUUMMP198lWE8h"},
    { title:"Always Tomorrow", artist:"Tokyo Tea Room", duration:	222523, vibe: 5, genre: "Alternative",link: "spotify:track:0OblxGfTmtALWjImtm7DFd"},
    { title:"Swallowtail Butterfly", artist:"BUBBLE TEA AND CIGARETTES", duration:	238000, vibe: 5, genre: "Alternative",link: "spotify:track:7fOrTmMQYXF50dZQwf2CE8"},
    { title:"煙火", artist:"夕陽武士", duration:	227426, vibe: 7, genre: "Rock",link: "spotify:track:5cVJ8dnMnFvJrutD50of67"},
    { title:"異鄉", artist:"非人物種", duration:	258986, vibe: 7, genre: "Rock",link: "spotify:track:1SqhuGVBoAlfI1mZNlepq5"},
    { title:"噪音公寓", artist:"Sorry Youth", duration:	198255, vibe: 7, genre: "Rock",link: "spotify:track:0HxFauxKj5X1DIujxM404U"},
    { title:"Six Boy", artist:"和平饭店", duration:	230159, vibe: 7, genre: "Alternative",link: "spotify:track:0iNDG1EAhquzA64gwZFvlm"},
    { title:"來不及", artist:"夕陽武士", duration:	270500, vibe: 8, genre: "Rock",link: "spotify:track:3pI5MHdKLlVC8krF7YdclS"},
    { title:"我常常有一種感覺", artist:"當代電影大師", duration:	238453, vibe: 8, genre: "Alternative",link: "spotify:track:7MOzpgUclb25mdkuFRghDx"},
    { title:"一個人", artist:"鹿洐人", duration:	227982, vibe: 8, genre: "Rock",link: "spotify:track:1yvxyDeTOQ5p6wgZYLp5bA"},
    { title:"擺渡人", artist:"非人物種", duration:	247880, vibe: 8, genre: "Rock",link: "spotify:track:1scivLbVNcXhSW3e0Oa2CS"},
    { title:"望時間會留", artist:"Sorry Youth", duration:	265176, vibe: 8, genre: "Rock",link: "spotify:track:5XxMOrekkWIvWMvvzAjeAX"},
    { title:"尾巴", artist:"和平饭店", duration:	321132, vibe: 8, genre: "Rock",link: "spotify:track:4SMYYHpRztA6AlBI6sr4kJ"},
    { title:"枉費青春", artist:"夕陽武士", duration:	271714, vibe: 9, genre: "Rock",link: "spotify:track:20ZFZ9CtlxAsq59cV5i3Hv"},
    { title:"羅馬假期", artist:"當代電影大師", duration:	137146, vibe: 9, genre: "Rock",link: "spotify:track:3uVeoqCXTukLsJKP4OxPz7"},
    { title:"鹽酥雞", artist:"鹿洐人", duration:	240579, vibe: 10, genre: "Rock",link: "spotify:track:1WIMlk1R6caj0JdukStWNO"},
    { title:"關於你娘的愛", artist:"非人物種", duration:	213773, vibe: 10, genre: "Rock",link: "spotify:track:4OcRktCYXobuqq9ydhqr1f"},
    { title:"世界第一戇", artist:"Sorry Youth, 謝銘祐", duration:	232295, vibe: 10, genre: "Rock",link: "spotify:track:3pwtXGyfbswOnjF0tNJpui"},
    { title:"屈勢", artist:"夕陽武士", duration:	202560, vibe: 10, genre: "Rock",link: "spotify:track:0s8ObKOybHBynfRNbbA4qS"},
    { title:"忘了把奇蹟帶來", artist:"Wayne's so Sad", duration:	262114, vibe: 10, genre: "Rock",link: "spotify:track:39wwpROjfg2jdKonvPTjmq"},
    { title:"你大概能看到那畫面從你的電視機", artist:"當代電影大師", duration:	169487, vibe: 10, genre: "Rock",link: "spotify:track:7qmFCXdozQtoURf4ttZA63"},
    { title:"爛笑話", artist:"鹿洐人", duration:	331682, vibe: 9, genre: "Rock",link: "spotify:track:198hnAbIhanHAmTISboPSQ"},
    { title:"塞你娘的愛", artist:"非人物種", duration:	211333, vibe: 7, genre: "Rock",link: "spotify:track:40YbZ3T1RisBXVsPpvtDPs"},
    { title:"踅夜市", artist:"Sorry Youth, JenJen", duration:	267118, vibe: 8, genre: "Rock",link: "spotify:track:0QTR1xpynHJJvKnLyOx1Zo"},
    { title:"牽手", artist:"夕陽武士, Queenie Fang", duration:	263500, vibe: 8, genre: "Rock",link: "spotify:track:3gEZfZ0szjPtfMNgiYsGuK"},
    { title:"欲壑", artist:"魚條", duration:	291960, vibe: 7, genre: "Alternative",link: "spotify:track:2yuVeQYfnaWRvIRr5atgEC"},
    { title:"年輕民謠", artist:"當代電影大師", duration:	278760, vibe: 6, genre: "Rock",link: "spotify:track:5BDCqXseCprrjMTs3jbZ2n"},
    { title:"雨", artist:"EmptyORio", duration:	172000, vibe: 6, genre: "Rock",link: "spotify:track:0Ou6DX7cbRYrofS4gLe88v"},
    { title:"鹹香", artist:"非人物種, CINEMAPHONIC", duration:	268565, vibe: 6, genre: "Alternative",link: "spotify:track:28UcT6qMkYv8jlLDKlEzGh"},
    { title:"暗流", artist:"Sorry Youth", duration:	432933, vibe: 5, genre: "Rock",link: "spotify:track:2JZtLMTPaS2HCf2T9FVDc6"},
    { title:"一刀讓我倒", artist:"夕陽武士", duration:	213257, vibe: 5, genre: "Rock",link: "spotify:track:6vW6zs5Fy6PpMcfsmAN8B0"},
    { title:"無聲", artist:"感覺莓果", duration:	252909, vibe: 9, genre: "Rock",link: "spotify:track:2Q6yhuzRh0YtBGjdMNMqvN"},
    { title:"陽台民謠", artist:"當代電影大師", duration:	408945, vibe: 7, genre: "Rock",link: "spotify:track:7FFsCBLfA9920pybOzpTyJ"},
    { title:"莫相信袂變卦", artist:"EmptyORio", duration:	218571, vibe: 8, genre: "Rock",link: "spotify:track:5cAZorLSY3kQ7Y9E1uvEbr"},
    { title:"大雨", artist:"Wayne's so Sad", duration:	239173, vibe: 8, genre: "Rock",link: "spotify:track:1dEz6J9ADmazhuoE1XT2nR"},
    { title:"你愛咱的無仝款", artist:"Sorry Youth", duration:	307980, vibe: 7, genre: "Rock",link: "spotify:track:6fepPbG2NZvf2RTRg0BOX0"},
    { title:"春夏秋冬", artist:"夕陽武士", duration:	295500, vibe: 7, genre: "Rock",link: "spotify:track:5pKT6WMtOihWjxm5zeqMSg"},
    { title:"來日不再是方長的夢", artist:"魚條", duration:	276026, vibe: 7, genre: "Rock",link: "spotify:track:6ZAzNLrDEhTASvkwkrFYol"},
    { title:"我知道他們是假貨", artist:"當代電影大師", duration:	150053, vibe: 5, genre: "Rock",link: "spotify:track:5vKg2tEe4pXZZxZ9aQ6Bf1"},
    { title:"登鸛雀樓", artist:"巨大的轟鳴 Gigantic Roar", duration:	256174, vibe: 6, genre: "Rock",link: "spotify:track:0T6xkyFQ67uLJEdx4JDf8E"},
    { title:"地平線之後", artist:"Wayne's so Sad", duration:	253746, vibe: 10, genre: "Rock",link: "spotify:track:2VPf3eP6Egg8CeGN0ApZ2l"},
    { title:"骨力走傱", artist:"Sorry Youth", duration:	330200, vibe: 7, genre: "Rock",link: "spotify:track:7gxVGvtYSVqOtV42FCZ1vQ"},
    { title:"好久不見（2022）", artist:"夕陽武士", duration:	196226, vibe: 7, genre: "Rock",link: "spotify:track:1OAh7vXzpCoo05k31cMQG3"},
    { title:"離開的意義", artist:"非人物種", duration:	298567, vibe: 9, genre: "Rock",link: "spotify:track:6YBZMuvIsJ4fTdzRtqtsIM"},
    { title:"我逆著走", artist:"當代電影大師", duration:	109853, vibe: 9, genre: "Rock",link: "spotify:track:6Huapu2cHUKzW6IGrkR7uI"},
    { title:"圈", artist:"犬儒乐队", duration:	350666, vibe: 10, genre: "Rock",link: "spotify:track:6TdcjxG4pdU1rJ6xkTk8JH"},
    { title:"母湯", artist:"打倒三明治", duration:	185226, vibe: 9, genre: "Rock",link: "spotify:track:20xopVlZeVWmXWxVWNEQHd"},
    { title:"歹勢中年", artist:"Sorry Youth", duration:	306982, vibe: 9, genre: "Rock",link: "spotify:track:6wnUozGyDEGl5dL19D7vHL"},
    { title:"風", artist:"夕陽武士", duration:	192303, vibe: 7, genre: "Rock",link: "spotify:track:4MdbLJONxO92jSVV9xzCTc"},
    { title:"失戀後的那個禮拜", artist:"Wayne's so Sad", duration:	89560, vibe: 5, genre: "Rock",link: "spotify:track:39jki0EA0F2CjS0sQboWpO"},
    { title:"告訴我他們都在本來的什麼地方", artist:"當代電影大師", duration:	154240, vibe: 5, genre: "Rock",link: "spotify:track:7feQVUhoh5a3s6CBoz48Cu"},
    { title:"在", artist:"hue", duration:	336545, vibe: 6, genre: "Rock",link: "spotify:track:1wqwiYc25D9Kyxkmofu40a"},
    { title:"浪漫人渣", artist:"打倒三明治", duration:	189226, vibe: 10, genre: "Rock",link: "spotify:track:0yYd1RwINc23lb4xRJowVx"},
    { title:"愛是啥貨", artist:"Sorry Youth", duration:	257614, vibe: 8, genre: "Rock",link: "spotify:track:6qfpstiA0pE7M7OUfzdD5V"},
    { title:"打開太陽", artist:"Flesh Juicer", duration:	295341, vibe: 10, genre: "Metal",link: "spotify:track:7x8ZvRVwqqTQGtGoL8rB75"},
    { title:"Master Of Puppets", artist:"Metallica", duration:	515386, vibe: 10, genre: "Metal",link: "spotify:track:2MuWTIM3b0YEAskbeeFE1i"},
    { title:"Ace of Spades", artist:"Motörhead", duration:	168320, vibe: 10, genre: "Metal",link: "spotify:track:3CIOopLwvyMvXk97ZEksKO"},
    { title:"護國山 Pattonkan", artist:"CHTHONIC", duration:	224670, vibe: 10, genre: "Metal",link: "spotify:track:3BJJwIvqrQYuUZieVHWa4w"},
    { title:"Forty-Nine Theurgy Chains", artist:"CHTHONIC", duration:	217160, vibe: 10, genre: "Metal",link: "spotify:track:76JqD6x21q3kDa2ehVvZvX"},
    { title:"關閉太陽", artist:"Flesh Juicer", duration:	340292, vibe: 10, genre: "Metal",link: "spotify:track:5qvvEvhJj9DghORIeaNOvm"},
    { title:"深海洋", artist:"Flesh Juicer", duration:	276214, vibe: 10, genre: "Metal",link: "spotify:track:1HXpbl8OSwRZ5YNdp3zRlt"},
    { title:"I Cum Blood", artist:"Cannibal Corpse", duration:	221960, vibe: 10, genre: "Death Metal",link: "spotify:track:3bQoMbPYOvvseHaSOWAQ3Q"},
    { title:"Psychosocial", artist:"Slipknot", duration:	284120, vibe: 10, genre: "Metal",link: "spotify:track:3RAFcUBrCNaboRXoP3S5t1"},
    { title:"Chop Suey!", artist:"System Of A Down", duration:	210240, vibe: 10, genre: "Metal",link: "spotify:track:2DlHlPMa4M17kufBvI2lEN"},
    { title:"Intro", artist:"No Party For Cao Dong", duration:	86653, vibe: 9, genre: "Rock",link: "spotify:track:2cM1D6jNpEc8XJjq5XUYl7"},
    { title:"醜", artist:"No Party For Cao Dong", duration:	117653, vibe: 8, genre: "Rock",link: "spotify:track:5Kc0fVPgQ808lwikSxCh70"},
    { title:"爛泥", artist:"No Party For Cao Dong", duration:	149506, vibe: 5, genre: "Rock",link: "spotify:track:6igC1CmfqGm8Xr7XW3lTO3"},
    { title:"勇敢的人", artist:"No Party For Cao Dong", duration:	220640, vibe: 9, genre: "Rock",link: "spotify:track:2JLenxeFclrYr9opG2mAjZ"},
    { title:"大風吹", artist:"No Party For Cao Dong", duration:	236080, vibe: 5, genre: "Rock",link: "spotify:track:52jaRS6n9DXbgf0Hd1sxlh"},
    { title:"艾瑪", artist:"No Party For Cao Dong", duration:	201506, vibe: 8, genre: "Rock",link: "spotify:track:3qmvcl9MczP5mcQjzpdwab"},
    { title:"等", artist:"No Party For Cao Dong", duration:	155986, vibe: 6, genre: "Rock",link: "spotify:track:20KSB3DRekMDCb31rY0ATd"},
    { title:"鬼", artist:"No Party For Cao Dong", duration:	160160, vibe: 8, genre: "Rock",link: "spotify:track:62vY0PxVWrAPAw8sSwf4d2"},
    { title:"在", artist:"No Party For Cao Dong", duration:	280280, vibe: 7, genre: "Rock",link: "spotify:track:64cl7ihf6pidqiukPUllig"},
    { title:"山海", artist:"No Party For Cao Dong", duration:	251053, vibe: 9, genre: "Rock",link: "spotify:track:0VUORVhLmsxKTSwg4P9CrB"},
    { title:"我們", artist:"No Party For Cao Dong", duration:	218626, vibe: 7, genre: "Rock",link: "spotify:track:6RInKT5dS6xsdD4s5SGyzH"},
    { title:"情歌", artist:"No Party For Cao Dong", duration:	256733, vibe: 9, genre: "Rock",link: "spotify:track:1sDV53WuMpn0q9hGpVFjtK"},
    { title:"苦難精算師", artist:"No Party For Cao Dong", duration:	245946, vibe: 6, genre: "Rock",link: "spotify:track:6eGUJXdHOrlprCeqohtlW3"},
    { title:"缸", artist:"No Party For Cao Dong", duration:	186506, vibe: 6, genre: "Rock",link: "spotify:track:2OL3D6q6Qs1PY0NV3u4dNu"},
    { title:"空", artist:"No Party For Cao Dong", duration:	177653, vibe: 6, genre: "Rock",link: "spotify:track:51LtYR0cpjc8wW33Dx0AWV"},
    { title:"人洞山", artist:"No Party For Cao Dong", duration:	207719, vibe: 8, genre: "Rock",link: "spotify:track:1sVa1skVE7TerpNTWVyrGh"},
    { title:"孑", artist:"No Party For Cao Dong", duration:	55321, vibe: 6, genre: "Rock",link: "spotify:track:1GJTIMW1qLe9Y7mv9IW0IL"},
    { title:"白日夢", artist:"No Party For Cao Dong", duration:	224626, vibe: 6, genre: "Rock",link: "spotify:track:5zpFUmekUFVlDjKDTuCbtl"},
    { title:"床", artist:"No Party For Cao Dong", duration:	232480, vibe: 10, genre: "Rock",link: "spotify:track:7iNnvOWQSTQPLn5WPu0gdU"},
    { title:"八", artist:"No Party For Cao Dong", duration:	226666, vibe: 5, genre: "Rock",link: "spotify:track:6DQYFsOi8HcYoCuqKPYSFq"},
    { title:"老張", artist:"No Party For Cao Dong", duration:	219120, vibe: 6, genre: "Rock",link: "spotify:track:08jNiT4cHNretoUfjZcHqm"},
    { title:"芽", artist:"No Party For Cao Dong", duration:	192226, vibe: 5, genre: "Rock",link: "spotify:track:0YvNutuR31gfnDFSSiVbld"},
    { title:"但", artist:"No Party For Cao Dong", duration:	142266, vibe: 5, genre: "Rock",link: "spotify:track:54hpc7UxPBdpcsC7xFKEWB"},
    { title:"如常", artist:"No Party For Cao Dong", duration:	186001, vibe: 7, genre: "Rock",link: "spotify:track:33AxZoUzOlBBbmr880MwLO"},
    { title:"還願", artist:"No Party For Cao Dong", duration:	225194, vibe: 10, genre: "Rock",link: "spotify:track:2Wew8zqBUtIXwZnxpIHdSf"},
    { title:"大大大大大象", artist:"動物園釘子戶", duration:	236357, vibe: 9, genre: "Alternative",link: "spotify:track:3HKy3cfRgoacaPuj4IlbpR"},
    { title:"人生模版", artist:"和平饭店", duration:	214807, vibe: 5, genre: "Alternative",link: "spotify:track:1k0ciIEjRzOgQY69auX7T8"},
    { title:"愚", artist:"hue", duration:	235738, vibe: 9, genre: "Rock",link: "spotify:track:72NsweUqjqV9pwJf1nmaSI"},
    { title:"日常", artist:"EggPlantEgg", duration:	243026, vibe: 5, genre: "Indie Pop",link: "spotify:track:7MLTCVNXFz5SFN84HSqYVg"},
    { title:"浪子回頭", artist:"EggPlantEgg", duration:	259372, vibe: 8, genre: "Rock",link: "spotify:track:2YA5IfmQwAmVzHRP3SVnEd"},
    { title:"愛情你比我想的閣較偉大 ", artist:"EggPlantEgg", duration:	232400, vibe: 9, genre: "Rock",link: "spotify:track:4fJlSLYLiu5trFCMZdSQDC"},
    { title:"這款自作多情", artist:"EggPlantEgg", duration:	290629, vibe: 5, genre: "Rock",link: "spotify:track:5UfEjWfz8TUck6ElbSAmbl"},
    { title:"孤獨的人我們一起出發", artist:"EggPlantEgg", duration:	264214, vibe: 9, genre: "Rock",link: "spotify:track:4BFErZk2BU6mfIaG7WOtHO"},
    { title:"窒息", artist:"EggPlantEgg", duration:	223804, vibe: 4, genre: "Indie Pop",link: "spotify:track:6n42pmQB6furMjFtnuI5zI"},
    { title:"現代的男女你如何看待", artist:"EggPlantEgg", duration:	209763, vibe: 7, genre: "Rock",link: "spotify:track:3zim0gHXKk6Gd3y2MQjqZQ"},
    { title:"浪流連", artist:"EggPlantEgg", duration:	253723, vibe: 8, genre: "Rock",link: "spotify:track:7a6VJHMS9ttKsj55cKC51G"},
    { title:"Happy!!! 運將情歌", artist:"EggPlantEgg", duration:	288363, vibe: 3, genre: "Indie Pop",link: "spotify:track:2BSHKKG0DxKtuNeV681tpU"},
    { title:"閣愛妳一擺", artist:"EggPlantEgg", duration:	278010, vibe: 7, genre: "Rock",link: "spotify:track:07plVccQ0N6FTTTonk3c2M"},
    { title:"Sweet Boy", artist:"Malcolm Todd", duration:	180000, vibe: 8, genre: "Alternative",link: "spotify:track:59c2xv2kMzYM6HR9oY6BIa"},
    { title:"Halcyon Age", artist:"Vansire", duration:	193379, vibe: 6, genre: "Alternative",link: "spotify:track:7C5pKQBh9xr7kCsBT6Y2n8"},
    { title:"Honey", artist:"Vacations", duration:	139605, vibe: 4, genre: "Alternative",link: "spotify:track:7IBzp33O4Hjr92wXtH3yQJ"},
    { title:"Seven", artist:"Men I Trust", duration:	225394, vibe: 3, genre: "Alternative",link: "spotify:track:5QvditjxADt1HMKPgaMjJm"},
    { title:"Roommates", artist:"Malcolm Todd", duration:	214504, vibe: 3, genre: "Alternative",link: "spotify:track:5vPUv0xziXbV4lnWeVNXNq"},
    { title:"Last Train At 25 O'clock", artist:"Lamp", duration:	263840, vibe: 7, genre: "Alternative",link: "spotify:track:3VPBPBZKxQu3bqeuzz8gRm"},
    { title:"I Think I Left the Stove On", artist:"Hotel Ugly", duration:	202490, vibe: 4, genre: "Alternative",link: "spotify:track:34HgIvucTKJvDgzHVMaGLG"},
    { title:"Sugar", artist:"Men I Trust", duration:	176315, vibe: 2, genre: "Indie Pop",link: "spotify:track:6ZdAsADC9LIICvsVRuGWbZ"},
    { title:"A Toshi no Aki", artist:"Lamp", duration:	248341, vibe: 3, genre: "J-Pop",link: "spotify:track:2QmfEczZyFTRhXJ9F81EP2"},
    { title:"All I Really Want Is You", artist:"The Marías", duration:	191800, vibe: 7, genre: "Indie Pop",link: "spotify:track:410rGaFDJPwjsr9m9RPCkz"},
    { title:"She Needs Him", artist:"Her's", duration:	314390, vibe: 6, genre: "Alternative",link: "spotify:track:1NjzNt18LlNTuJYErYGvbQ"},
    { title:"Come Over And Love Me", artist:"Love Spells", duration:	161266, vibe: 2, genre: "Pop",link: "spotify:track:17zIQS6XlXzyJFIZoGcs1n"},
    { title:"Amoeba", artist:"Clairo", duration:	228922, vibe: 7, genre: "Alternative",link: "spotify:track:0HAqq2GcQKyi3s87GuN7jU"},
    { title:"Oncle Jazz", artist:"Men I Trust", duration:	57876, vibe: 8, genre: "Alternative",link: "spotify:track:204t5SErksNRHRhU52g5JF"},
    { title:"Next Exit", artist:"Vacations", duration:	201000, vibe: 2, genre: "Alternative",link: "spotify:track:3aI2wWEeNmtYDvsAyJahyi"},
    { title:"Run Away", artist:"Chezile", duration:	159650, vibe: 2, genre: "Alternative",link: "spotify:track:6doY5sLPHdE4g7RUQdYSz6"},
    { title:"蓋なしの彼", artist:"mei ehara", duration:	230266, vibe: 2, genre: "J-Pop",link: "spotify:track:7MzKmI0Ep4dFRfTeQ9RtpZ"},
    { title:"still love you (todavía)", artist:"The Tulips", duration:	152234, vibe: 4, genre: "Alternative",link: "spotify:track:6ggzIOQ1wbVWjpGOzJvoqF"},
    { title:"Stevie Doesn't Wonder", artist:"Hotel Ugly", duration:	164571, vibe: 7, genre: "Alternative",link: "spotify:track:7BgyWwbbybJr2IbQoI1gzH"},
    { title:"Just the Right Song", artist:"Vansire", duration:	186253, vibe: 6, genre: "Pop",link: "spotify:track:4P3mcaMeif02CSqx6MAleZ"},
    { title:"She Won't Go Away", artist:"Faye Webster", duration:	185646, vibe: 7, genre: "Alternative",link: "spotify:track:5sGGlfbqdGlJr3ZMMjODoy"},
    { title:"Care For You", artist:"The Marías", duration:	156026, vibe: 7, genre: "Pop",link: "spotify:track:2CBtdZVcpSwaxOcLUi1AGo"},
    { title:"Natural", artist:"Shelly", duration:	163764, vibe: 2, genre: "Pop",link: "spotify:track:6VLjdregMReJhKp2r32IWo"},
    { title:"Le château", artist:"Ginger Root", duration:	155855, vibe: 3, genre: "Alternative",link: "spotify:track:3KhPLLQjXodVQU9FoIlCUh"},
    { title:"That I Miss You", artist:"Vansire", duration:	140116, vibe: 6, genre: "Alternative",link: "spotify:track:7szBZqBJuj9eAC8HJ4CyTM"},
    { title:"Summer's Over", artist:"Jordana, TV Girl", duration:	173000, vibe: 3, genre: "Alternative",link: "spotify:track:4E5N0mYyYFf0QZs3XDeSIj"},
    { title:"Little by Little", artist:"The Marías", duration:	178493, vibe: 4, genre: "Alternative",link: "spotify:track:3EzlgdxyFvjeAGzR5WxHB8"},
    { title:"Steeeam", artist:"Shelly", duration:	170892, vibe: 5, genre: "Alternative",link: "spotify:track:09RamrocZneYcLYLRIxYha"},
    { title:"Metamodernity", artist:"Vansire", duration:	162663, vibe: 6, genre: "Alternative",link: "spotify:track:4RGWHfQeJftd5XrP8JUgFj"},
    { title:"Right Side of My Neck", artist:"Faye Webster", duration:	153320, vibe: 6, genre: "Alternative",link: "spotify:track:3cxZT78mZDyLsLPJKcTu3U"},
    { title:"Jupiter", artist:"Matt Maltese", duration:	168852, vibe: 8, genre: "Alternative",link: "spotify:track:3kg7A13eqXpZnnyXEVcGsj"},
    { title:"apart of me", artist:"Takayoshi", duration:	76285, vibe: 7, genre: "Alternative",link: "spotify:track:2D79qw6Zobv0O7MMD74V6C"},
    { title:"Away", artist:"Vacations", duration:	162333, vibe: 3, genre: "Alternative",link: "spotify:track:2NaGl56lq71UMzDSI8jmJ3"},
    { title:"Sun Outside My Window", artist:"Strawberry Guy", duration:	201226, vibe: 2, genre: "Alternative",link: "spotify:track:5fCqHoueAR1Q790mPKj1HR"},
    { title:"Estrangers", artist:"No Vacation", duration:	199000, vibe: 2, genre: "Alternative",link: "spotify:track:6WGhBQvC1ocDzUA60S4hUH"},
    { title:"2516", artist:"Luna Li", duration:	68000, vibe: 6, genre: "Alternative",link: "spotify:track:0R6sz2EUOMSM3qaZHEpG63"},
    { title:"Jellyfish", artist:"落日飛車 Sunset Rollercoaster, Michael Seyer", duration:	221374, vibe: 2, genre: "Alternative",link: "spotify:track:7Fz2DZx9evgMkp6K79a3sj"},
    { title:"My Jinji", artist:"落日飛車 Sunset Rollercoaster", duration:	400560, vibe: 4, genre: "Alternative",link: "spotify:track:59Bc4RPzSL3nYPANh25a6J"},
    { title:"Let There Be Light Again", artist:"落日飛車 Sunset Rollercoaster", duration:	227293, vibe: 8, genre: "Alternative",link: "spotify:track:4Anip7bDkwKk4HacAIwvEl"},
    { title:"Travel Agency", artist:"落日飛車 Sunset Rollercoaster", duration:	294265, vibe: 3, genre: "Alternative",link: "spotify:track:5eymdfr6m3gB2lMemXwvIX"},
    { title:"Villa", artist:"落日飛車 Sunset Rollercoaster", duration:	161803, vibe: 2, genre: "Alternative",link: "spotify:track:0BCmwpQfnx8N9wnX493XhT"},
    { title:"小薇", artist:"落日飛車 Sunset Rollercoaster", duration:	259250, vibe: 7, genre: "Alternative",link: "spotify:track:1N4KmpLLvuWV5RcF7eI8JS"},
    { title:"忘情水", artist:"落日飛車 Sunset Rollercoaster", duration:	265386, vibe: 2, genre: "Alternative",link: "spotify:track:3N3xDs2Z4s5bVmiN2ZAK1J"},
    { title:"Line by Line", artist:"PREP, Cory Wong, Paul Jackson\, Jr.", duration:	237786, vibe: 4, genre: "Alternative",link: "spotify:track:2Q2KyAJe3CZbBFLIjo3F3Z"},
    { title:"Don't Look Back", artist:"PREP, So!YoON!, SHOWNU (MONSTA X)", duration:	271800, vibe: 7, genre: "Alternative",link: "spotify:track:5rul18hLz6lR3s4c9URUDL"},
    { title:"Leaning on You", artist:"PREP", duration:	199973, vibe: 7, genre: "Alternative",link: "spotify:track:1Oo0XRrDDEeF8rh7e0uZGw"},
    { title:"I Can't Answer That", artist:"PREP", duration:	246706, vibe: 3, genre: "Alternative",link: "spotify:track:3UkWgTbTdxYlGchZQEVu1A"},
    { title:"Freaking Out the Neighborhood", artist:"Mac DeMarco", duration:	173888, vibe: 5, genre: "Alternative",link: "spotify:track:3HlK8txWAdtKMrbsqX40pl"},
    { title:"My Kind of Woman", artist:"Mac DeMarco", duration:	190845, vibe: 2, genre: "Alternative",link: "spotify:track:6jgkEbmQ2F2onEqsEhiliL"},
    { title:"Another One", artist:"Mac DeMarco", duration:	160991, vibe: 5, genre: "Alternative",link: "spotify:track:63q9LqTK5iiZLy3cTvLMUf"},
    { title:"Goodbye Weekend", artist:"Mac DeMarco", duration:	179766, vibe: 4, genre: "Alternative",link: "spotify:track:7veyzFpXGgZj5Ul3TZ1lBc"},
    { title:"Chamber Of Reflection", artist:"Mac DeMarco", duration:	231723, vibe: 3, genre: "Alternative",link: "spotify:track:7H7NyZ3G075GqPx2evsfeb"},
    { title:"Go Easy", artist:"Mac DeMarco", duration:	204901, vibe: 3, genre: "Alternative",link: "spotify:track:2ypibq9nMJtHCNLyNUubJj"},
    { title:"サマー・サンバ", artist:"Lisa Ono", duration:	134954, vibe: 3, genre: "Samba",link: "spotify:track:7ml7zxSdgRW330pn8eNy9h"},
    { title:"ソ・ダンソ・サンバ", artist:"Lisa Ono", duration:	155693, vibe: 6, genre: "Samba",link: "spotify:track:0LueIFiaHprxvc8fJOhFKm"},
    { title:"Samba de mon cœur qui bat", artist:"Coralie Clement", duration:	233960, vibe: 3, genre: "Samba",link: "spotify:track:4zXKbHN9FKRTIirYQdMRqI"},
    { title:"Take Five", artist:"The Dave Brubeck Quartet", duration:	324133, vibe: 6, genre: "Jazz",link: "spotify:track:1YQWosTIljIvxAgHWTp7KP"},
    { title:"Autumn Leaves", artist:"Chet Baker", duration:	422333, vibe: 2, genre: "Jazz",link: "spotify:track:10ZirIXPKWSj0aFLOvpDEs"},
    { title:"LA VIE EN ROSE", artist:"Lisa Ono", duration:	284106, vibe: 2, genre: "Jazz",link: "spotify:track:6qIxVMI28YeGea2hBlmQQa"},
    { title:"jazz is for ordinary people", artist:"berlioz", duration:	164000, vibe: 5, genre: "Jazz",link: "spotify:track:12BaQt9aYdTlEtKreqB5V4"},
    { title:"Spain", artist:"Chick Corea, Return To Forever", duration:	589093, vibe: 3, genre: "Jazz",link: "spotify:track:0YhaRPBhAVHZcdileuPtJM"},
    { title:"ひとひら", artist:"Blu-Swing", duration:	165626, vibe: 6, genre: "Jazz",link: "spotify:track:0NsQs28wv5MGAXq5Mw6xzh"},
    { title:"One Beer", artist:"MF DOOM", duration:	258586, vibe: 3, genre: "Hip-Hop",link: "spotify:track:4BnrGx9tWNF8aiXl1UhDBa"},
    { title:"Rapp Snitch Knishes", artist:"MF DOOM, Mr. Fantastik", duration:	172893, vibe: 3, genre: "Hip-Hop",link: "spotify:track:5KUNwkaNf8l5A9sXZhiCgI"},
    { title:"Doomsday", artist:"MF DOOM, Pebbles The Invisible Girl", duration:	298053, vibe: 2, genre: "Hip-Hop",link: "spotify:track:7EQvdUJqZ2i7SWvSB2VqGA"},
    { title:"Arrival", artist:"The Alchemist", duration:	94967, vibe: 2, genre: "Hip-Hop",link: "spotify:track:6quMGNh47CpSR5kmZSYSTK"},
    { title:"Every Breath You Take", artist:"The Police", duration:	253920, vibe: 5, genre: "New Wave",link: "spotify:track:1JSTJqkT5qHq8MDJnJbRE1"},
    { title:"Every Little Thing She Does Is Magic", artist:"The Police", duration:	260573, vibe: 3, genre: "New Wave",link: "spotify:track:44aTAUBF0g6sMkMNE8I5kd"},
    { title:"Message In A Bottle", artist:"The Police", duration:	290280, vibe: 6, genre: "New Wave",link: "spotify:track:1oYYd2gnWZYrt89EBXdFiO"},
    { title:"Take on Me", artist:"a-ha", duration:	225280, vibe: 3, genre: "New Wave",link: "spotify:track:2WfaOiMkCvy7F5fcp2zZ8L"},
    { title:"Virtual Insanity", artist:"Jamiroquai", duration:	227840, vibe: 7, genre: "Acid Jazz",link: "spotify:track:24SUWisv2lYQiB3bVpE1sn"},
    { title:"I Want To Break Free", artist:"Queen", duration:	199533, vibe: 7, genre: "Rock",link: "spotify:track:1IVZX29ZuEXng3ChRnp3tL"},
    { title:"Under Pressure", artist:"Queen, David Bowie", duration:	248440, vibe: 6, genre: "Rock",link: "spotify:track:11IzgLRXV7Cgek3tEgGgjw"},
    { title:"Don't Stop Me Now", artist:"Queen", duration:	209413, vibe: 6, genre: "Rock",link: "spotify:track:7hQJA50XrCWABAu5v6QZ4i"},
    { title:"Bohemian Rhapsody", artist:"Queen", duration:	354320, vibe: 3, genre: "Rock",link: "spotify:track:5eIDxmWYxRA0HJBYM9bIIS"},
    { title:"Rocket Man (I Think It's Going To Be A Long, Long Time)", artist:"Elton John", duration:	281613, vibe: 7, genre: "Rock",link: "spotify:track:3gdewACMIVMEWVbyb8O9sY"},
    { title:"Comfortably Numb", artist:"Pink Floyd", duration:	382296, vibe: 6, genre: "Rock",link: "spotify:track:5HNCy40Ni5BZJFw1TKzRsC"},
    { title:"Imagine ", artist:"John Lennon", duration:	187866, vibe: 5, genre: "Pop",link: "spotify:track:7pKfPomDEeI4TPT6EOYjn9"},
    { title:"The Chain", artist:"Fleetwood Mac", duration:	271000, vibe: 7, genre: "Rock",link: "spotify:track:2X6gdRlGOQgfaXU9ALUQFQ"},
    { title:"Space Oddity", artist:"David Bowie", duration:	318026, vibe: 4, genre: "Pop",link: "spotify:track:72Z17vmmeQKAg8bptWvpVG"},
    { title:"You're My Best Friend", artist:"Queen", duration:	170800, vibe: 3, genre: "Rock",link: "spotify:track:4OKf7CcYuw5H2HptkcKxcP"},
    { title:"Escape (The Pina Colada Song)", artist:"Rupert Holmes", duration:	276493, vibe: 3, genre: "Rock",link: "spotify:track:5IMtdHjJ1OtkxbGe4zfUxQ"},
    { title:"Dreams - 2004 Remaster", artist:"Fleetwood Mac", duration:	257800, vibe: 3, genre: "Rock",link: "spotify:track:0ofHAoxe9vBkTCp2UQIavz"},
    { title:"Changing", artist:"Ice Cream Boy", duration:	258490, vibe: 6, genre: "Alternative",link: "spotify:track:6sITVdQCU8aLqPNDJVK2LK"},
    { title:"I'd Love to Change the World", artist:"Ten Years After", duration:	224133, vibe: 5, genre: "Rock",link: "spotify:track:19HjHUjCfDrEYhVSIKG6nK"},
    { title:"Hey Hey Baby", artist:"my little airport", duration:	139186, vibe: 5, genre: "Indie Pop",link: "spotify:track:2Mh7XNWkAXgEjBXSskgUyD"},
    { title:"Baba O'Riley", artist:"The Who", duration:	300400, vibe: 5, genre: "Rock",link: "spotify:track:3qiyyUfYe7CRYLucrPmulD"},
    { title:"Starman", artist:"David Bowie", duration:	254293, vibe: 6, genre: "Rock",link: "spotify:track:0pQskrTITgmCMyr85tb9qq"},
    { title:"Highway to Hell", artist:"AC/DC", duration:	208400, vibe: 6, genre: "Rock",link: "spotify:track:2zYzyRzz6pRmhPzyfMEC8s"},
    { title:"Demon Fire", artist:"AC/DC", duration:	210360, vibe: 3, genre: "Rock",link: "spotify:track:6jtUOVRO4p09Z7E35ERRL7"},
    { title:"You Shook Me All Night Long", artist:"AC/DC", duration:	210173, vibe: 5, genre: "Rock",link: "spotify:track:2SiXAy7TuUkycRVbbWDEpo"},
    { title:"モノクローム", artist:"Naoko Gushima", duration:	337933, vibe: 6, genre: "J-Pop",link: "spotify:track:1BVEBGbZTgBmtWm54cTSs0"},
    { title:"エイリアンズ", artist:"KIRINJI", duration:	364333, vibe: 5, genre: "Indie Pop",link: "spotify:track:5NclFtKE9l08xM8XhDKyzx"},
    { title:"秘密", artist:"Zhang Zhen Yue", duration:	322573, vibe: 4, genre: "Rock",link: "spotify:track:7yORKhsiAJB0jKaPiASEf1"},
    { title:"被動", artist:"Wu Bai", duration:	271866, vibe: 6, genre: "Rock",link: "spotify:track:5XhE0o2mWyd597AVl5a8ry"},
    { title:"憂愁", artist:"小安", duration:	282733, vibe: 4, genre: "Pop",link: "spotify:track:6KhIdXJVEnOMzmbIhj1yxw"},


];

const container = document.getElementById("musicBlocks");

songs.forEach(song => {
    const block = document.createElement("div");
    block.classList.add("block");
    block.style.height = `${song.vibe * 30}px`;
    block.style.width = `${song.duration / 1000 * 0.12}px`; 
    block.style.backgroundColor = genreColors[song.genre] || "#cccccc";

    const info = document.createElement("div");
    function str_pad_left(string, pad, length) {
        return (new Array(length + 1).join(pad) + string).slice(-length);
      }
    const min = Math.floor(song.duration / 60000);
    const sec = ((song.duration % 60000) / 1000).toFixed(0);
    const finalTime = str_pad_left(min, '0', 2) + ':' + str_pad_left(sec, '0', 2);
    
    info.classList.add("song-info");
    info.innerHTML = `
        <strong>${song.title}</strong><br>
        <small>by ${song.artist}</small><br>
        <small>Duration: ${finalTime}</small><br>
        <small>Genre: ${song.genre}</small>
    `;
    
    info.style.width = `${200 + (song.title.length)*1.1 }px`;

    block.addEventListener('click', () => {
        window.open(song.link, '_blank');
    });

    block.appendChild(info);
    container.appendChild(block);
});
